DEVICE_TYPE_ID_MISSING_ERROR_MSG = 'Missing device type id.'
DEVICE_TYPE_ID_INCORRECT_ERROR_MSG = 'Incorrect device type id.'
DEVICE_TYPE_DESC_MISSING_ERROR_MSG = 'Missing device type description.'
DEVICE_NAME_BI_MISSING_ERROR_MSG = 'Missing device Blind Index.'
DEVICE_NAME_MISSING_ERROR_MSG = 'Missing device Name.'
DEVICE_NAME_INVALID_ERROR_MSG = 'Device ID is invalid.'
DATA_RANGE_MISSING_ERROR_MSG = 'Missing upper and lower range for query.'
DATA_OUT_OF_OUTPUT_RANGE_ERROR_MSG = 'Value out of OPE output range.'
CORRECTNESS_HASH_MISSING_ERROR_MSG = 'Correctness Hash needs to be provided.'
DEVICE_ID_MISSING_ERROR_MSG = 'Missing device id.'
PUBLIC_KEY_MISSING_ERROR_MSG = 'Missing user public key for key exchange.'
UNAUTHORIZED_USER_ERROR_MSG = 'Specified user is not authorized to use this device.'
NO_PUBLIC_KEY_ERROR_MSG = 'No public key available for this device.'

MASTER_KEY_MISSING_ERROR_MSG = 'Missing serialized master key argument.'
ATTR_LIST_MISSING_ERROR_MSG = 'Missing attribute list argument.'
RECEIVER_ID_MISSING_ERROR_MSG = 'Missing receiver id argument.'
INCORRECT_RECEIVER_ID_ERROR_MSG = 'Incorrect receiver ID.'
INVALID_ATTR_LIST_ERROR_MSG = 'Invalid attribute list (only alphanumeric values separated with whitespaces are allowed).'
MESSAGE_MISSING_ERROR_MSG = 'Missing plaintext message to be encrypted.'
POLICY_STRING_MISSING_ERROR_MSG = 'Missing Policy string in format `((four or three) and (two or one))`'
CIPHERTEXT_MISSING_ERROR_MSG = 'Missing ciphertext to be decrypted.'
COULD_NOT_DECRYPT_ERROR_MSG = "We could not decrypt your message (MAC might be invalid = Your data was tampered with or your key is wrong)."
INVALID_OWNER_API_USERNAME_ERROR_MSG = 'Specified API username of data owner is invalid.'
OWNER_API_USERNAME_MISSING_ERROR_MSG = 'Specified API username of data owner is invalid is not present.'
API_USERNAME_MISSING_ERROR_MSG = 'Missing API username argument.'

SOMETHING_WENT_WRONG_MSG = "Something went wrong..."
