#!/bin/bash
set -e

POSTGRES="psql --username ${POSTGRES_USER}"

echo "Creating database: ${TESTING_DB_NAME}"

$POSTGRES <<EOSQL
CREATE DATABASE ${TESTING_DB_NAME} OWNER ${POSTGRES_USER};
EOSQL

echo "Creating database: ${ATTR_AUTH_DB_NAME}"

$POSTGRES <<EOSQL
CREATE DATABASE ${ATTR_AUTH_DB_NAME} OWNER ${POSTGRES_USER};
EOSQL

echo "Creating database: ${TEST_DB_ATTR_AUTH_NAME}"

$POSTGRES <<EOSQL
CREATE DATABASE ${TEST_DB_ATTR_AUTH_NAME} OWNER ${POSTGRES_USER};
EOSQL
