version: '3'
services:
  db:
    build: ./
    container_name: iot_cloud_db
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - 5430
    ports:
      - 5430:5430
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      TESTING_DB_NAME: "testing"
      ATTR_AUTH_DB_NAME: "attr_auth"
      TEST_DB_ATTR_AUTH_NAME: "attr_auth_testing"
      POSTGRES_DB: postgres
      PGPORT: 5430
    networks:
      - iot-cloud_test

volumes:
  data: {}

networks:
  iot-cloud_test:
    external: true